name: Pytest

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Run tests and save output
        id: pytest
        run: |

           uv run pytest -v >> test_result.txt

      - name: send telegram message on push
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: test_result.txt
          message: |
            Status: ${{ job.status }}
            