name: Pytest

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run console log
        run: echo "Hello GitHub Actions!"

      - name: tdjkdhs
        run: ls
