name: Pytest

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: tests
        run: uv run pytest

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |

            hi
            # ${{ github.actor }} created commit:
            # Commit message: ${{ github.event.commits[0].message }}
            
            # Repository: ${{ github.repository }}
            
            # See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


