name: Pytest

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: tests
        run: uv run pytest


